
#Text Engine Config
[text]
	#Allow text renderer to drop shadow, setting to false can improve performance.
	allowShadow = true
	#Fix resolution level at 2. When the GUI scale increases, the resolution level remains.
	#Then GUI scale should be even numbers (2, 4, 6...), based on Minecraft GUI system.
	#If your fonts are not bitmap fonts, then you should keep this setting false.
	fixedResolution = false
	#Control base font size, in GUI scaled pixels. The default and vanilla value is 8.
	#For bitmap fonts, 8 represents a glyph size of 8x or 16x if fixed resolution.
	#Range: 6.5 ~ 9.5
	baseFontSize = 8.0
	#Control vertical baseline for vanilla text layout, in GUI scaled pixels.
	#The vanilla default value is 7.
	#Range: 4.0 ~ 10.0
	baselineShift = 7.0
	#Control the text shadow offset for vanilla text rendering, in GUI scaled pixels.
	#Range: 0.20000000298023224 ~ 2.0
	shadowOffset = 0.8
	#Control the text outline offset for vanilla text rendering, in GUI scaled pixels.
	#Range: 0.20000000298023224 ~ 2.0
	outlineOffset = 0.5
	#The bidirectional text heuristic algorithm.
	#This will affect which BiDi algorithm to use during text layout.
	#Allowed Values: FIRST_STRONG, ANY_RTL, LTR, RTL, LOCALE, FIRST_STRONG_LTR, FIRST_STRONG_RTL
	textDirection = "FIRST_STRONG"
	#Whether to use Google Noto Color Emoji, otherwise grayscale emoji (faster).
	#See Unicode 15.0 specification for details on how this affects text layout.
	useColorEmoji = true
	#Allow Slack or Discord shortcodes to replace Unicode Emoji Sequences in chat.
	emojiShortcodes = true
	#Whether to use Modern UI text rendering pipeline in 3D world.
	#Disabling this means that SDF text and rendering optimization are no longer effective.
	#But text rendering can be compatible with OptiFine Shaders and Iris Shaders.
	#This does not affect text rendering in GUI.
	useTextShadersInWorld = true
	#For DEFAULT_FONT and UNIFORM_FONT, should we keep some bitmap providers of them?
	#Ignore All: Use selectedTypeface only.
	#Keep ASCII: Include minecraft:font/ascii.png, minecraft:font/accented.png, minecraft:font/nonlatin_european.png
	#Keep Other: Include providers in minecraft:font/default.json other than Keep ASCII and Unicode font.
	#Keep All: Include all except Unicode font.
	#Allowed Values: IGNORE_ALL, KEEP_ASCII, KEEP_OTHER, KEEP_ALL
	defaultFontBehavior = "KEEP_OTHER"
	#Whether to use text component object as hash key to lookup in layout cache.
	#If you find that Modern UI text rendering is not compatible with some mods,
	#you can disable this option for compatibility, but this will decrease performance a bit.
	useComponentCache = true

